//
//  PreLevelCreateRouter.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 03.04.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PreLevelCreateRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol PreLevelCreateDataPassing
{
  var dataStore: PreLevelCreateDataStore? { get }
}

class PreLevelCreateRouter: NSObject, PreLevelCreateRoutingLogic, PreLevelCreateDataPassing
{
  weak var viewController: PreLevelCreateViewController?
  var dataStore: PreLevelCreateDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: PreLevelCreateViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: PreLevelCreateDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
