//
//  PreLevelCreateInteractor.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 03.04.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PreLevelCreateBusinessLogic
{
    func fillDataStore(request: PreLevelCreate.FillDataStore.Request)
}

protocol PreLevelCreateDataStore
{
    var songId: String? {get set}
    var levelName: String? {get set}
    var linesAmount: Int? {get set}
    var speed: Int? {get set}
}

class PreLevelCreateInteractor: PreLevelCreateBusinessLogic, PreLevelCreateDataStore
{
    var linesAmount: Int?
    var levelName: String?
    var songId: String?
    var speed: Int?
    
    var presenter: PreLevelCreatePresentationLogic?
    var worker: PreLevelCreateWorker?
    
    func fillDataStore(request: PreLevelCreate.FillDataStore.Request)
    {
        self.levelName = request.levelName
        self.linesAmount = request.linesCount
        self.speed = request.speed
    }
}
