//
//  PreLevelCreateViewController.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 03.04.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PreLevelCreateDisplayLogic: class
{
}

class PreLevelCreateViewController: UIViewController, PreLevelCreateDisplayLogic
{
    
    
    @IBOutlet weak var levelName: UITextField!
    
    @IBOutlet weak var lineAmountLabel: UILabel!
    
    @IBOutlet weak var speedLabel: UILabel!
    
    private var lineAmount: Int? = 3
    private var speed: Int? = 500
    
    @IBAction func lineChanged(_ sender: Any) {
        if let sender = sender as? UIStepper{
            lineAmountLabel.text = "\(sender.value.int)"
            lineAmount = sender.value.int
        }
    }
    
    @IBAction func speedChanged(_ sender: Any) {
        if let sender = sender as? UIStepper{
            speedLabel.text = "\(sender.value.int)"
            speed = sender.value.int
        }
    }
    
    @IBAction func createPressed(_ sender: Any) {
        guard let destination = storyboard?.instantiateViewController(withIdentifier: "LevelCreateViewController") as? LevelCreateViewController else { return }
        
        destination.songId = (interactor as? PreLevelCreateDataStore)?.songId
        destination.levelName = levelName.text ?? "level"
        destination.lineAmount = lineAmount
        destination.speed = speed
        
        show(destination, sender: self)
    }
    
    
    
    var interactor: PreLevelCreateBusinessLogic?
    var router: (NSObjectProtocol & PreLevelCreateRoutingLogic & PreLevelCreateDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = PreLevelCreateInteractor()
        let presenter = PreLevelCreatePresenter()
        let router = PreLevelCreateRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
}
