//
//  LevelSelectRouter.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 24.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LevelSelectRoutingLogic
{
    func routeToPreLevelCreate(segue: UIStoryboardSegue?)
}

protocol LevelSelectDataPassing
{
    var dataStore: LevelSelectDataStore? { get }
}

class LevelSelectRouter: NSObject, LevelSelectRoutingLogic, LevelSelectDataPassing
{
    weak var viewController: LevelSelectViewController?
    var dataStore: LevelSelectDataStore?
    
    // MARK: Routing
    
    func routeToPreLevelCreate(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! PreLevelCreateViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToPreLevelCreate(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "PreLevelCreateViewController") as! PreLevelCreateViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToPreLevelCreate(source: dataStore!, destination: &destinationDS)
            navigateToPreLevelCreate(source: viewController!, destination: destinationVC)
        }
    }
    
    func navigateToPreLevelCreate(source: LevelSelectViewController, destination: PreLevelCreateViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func passDataToPreLevelCreate(source: LevelSelectDataStore, destination: inout PreLevelCreateDataStore)
    {
        destination.songId = source.songId
    }
}
