//
//  LevelSelectRouter.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 24.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LevelSelectRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LevelSelectDataPassing
{
  var dataStore: LevelSelectDataStore? { get }
}

class LevelSelectRouter: NSObject, LevelSelectRoutingLogic, LevelSelectDataPassing
{
  weak var viewController: LevelSelectViewController?
  var dataStore: LevelSelectDataStore?
  
  // MARK: Routing
  
//  func routeToSomewhere(segue: UIStoryboardSegue?)
//  {
//    if let segue = segue {
//      let destinationVC = segue.destination as! GameViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "GameViewController") as! GameViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
//  }
//  
//  func navigateToSomewhere(source: LevelSelectViewController, destination: GameViewController)
//  {
//    source.show(destination, sender: nil)
//  }
//  
//  func passDataToSomewhere(source: LevelSelectDataStore, destination: inout SomewhereDataStore)
//  {
//    destination.name = source.name
//  }
}
