//
//  LevelSelectPresenter.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 24.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LevelSelectPresentationLogic
{
    func presentLevels(response: LevelSelect.Something.Response)
}

class LevelSelectPresenter: LevelSelectPresentationLogic
{
    weak var viewController: LevelSelectDisplayLogic?
    
    func presentLevels(response: LevelSelect.Something.Response)
    {
        let viewModel = LevelSelect.Something.ViewModel(levels: response.levels)
        viewController?.displayLevels(viewModel: viewModel)
    }
}
