//
//  LevelSelectModels.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 24.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LevelSelect
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
            var levels : [Level]
        }
        struct ViewModel
        {
            var levels : [Level]
        }
    }
}
