//
//  LevelSelectInteractor.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 24.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LevelSelectBusinessLogic
{
    func loadLevels(request: LevelSelect.Something.Request)
}

protocol LevelSelectDataStore
{
    var songId : String? { get set }
    var levels: [Level]? { get set }
}

class LevelSelectInteractor: LevelSelectBusinessLogic, LevelSelectDataStore
{
    
    init(){
        worker = LevelSelectWorker()
    }
    
    var songId: String?
    var levels: [Level]?
    
    var presenter: LevelSelectPresentationLogic?
    var worker: LevelSelectWorker?
    
    // MARK: Do something
    
    func loadLevels(request: LevelSelect.Something.Request)
    {
        worker = LevelSelectWorker()
        if let id = songId{
            worker?.loadLevels(for: id, onSuccess: { (levels) in
                let response = LevelSelect.Something.Response(levels: levels)
                presenter?.presentLevels(response: response)
            })        
        }
    }
}
