//
//  SongSearchRouter.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 08.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SongSearchRoutingLogic
{
    func routeToLevelSelect(segue: UIStoryboardSegue?)
}

protocol SongSearchDataPassing
{
    var dataStore: SongSearchDataStore? { get }
}

class SongSearchRouter: NSObject, SongSearchRoutingLogic, SongSearchDataPassing
{
    weak var viewController: SongSearchViewController?
    var dataStore: SongSearchDataStore?
    
    // MARK: Routing
    
    func routeToLevelSelect(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! LevelSelectViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLevelSelect(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "LevelSelectViewController") as! LevelSelectViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLevelSelect(source: dataStore!, destination: &destinationDS)
            navigateToLevelSelect(source: viewController!, destination: destinationVC)
        }
    }
    
    func navigateToLevelSelect(source: SongSearchViewController, destination: LevelSelectViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func passDataToLevelSelect(source: SongSearchDataStore, destination: inout LevelSelectDataStore)
    {
        let row = viewController?.collectionView.indexPathsForSelectedItems?.first?.row
        if let row = row{
            destination.songId = source.data[row].identifier
        }
    }
}
