//
//  SongSearchWorker.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 08.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Parse

class SongSearchWorker
{
    let manager: AppleMusicManager
    let authorization: AuthorizationManager
    init(){
        manager = AppleManager.instance.appleMusicManager
        authorization = AppleManager.instance.authorizationManager
    }
    
    func search(for query: String, onComplete: @escaping ([MediaItem])->Void)
    {
        manager.performAppleMusicCatalogSearch(
            with: query,
            countryCode: authorization.cloudServiceStorefrontCountryCode) { (items, error) in
                if items.count > 0{
                    onComplete(items[0])
                }
        }
    }
    
    func recent(onComplete: @escaping ([MediaItem])->Void)
    {
        manager.performAppleMusicGetRecentlyPlayed(userToken: authorization.userToken, completion: { (items, error) in
            onComplete(items)
        })
    }
    
    func songsWithLevels(onComplete: @escaping ([MediaItem])->Void){
        let query = PFQuery(className: "Level").addDescendingOrder("rating").selectKeys(["songId"])
        
        query.findObjectsInBackground { (pfos, error) in
            if let error = error{
                print(error.localizedDescription)
            }
            
            if let pfos = pfos{
                let ids = pfos.map({ (pfo) -> String in
                    return pfo["songId"] as? String ?? ""
                })
                self.manager.performAppleMusicSongsRequest(
                    ids: ids,
                    countryCode: self.authorization.cloudServiceStorefrontCountryCode, completion: { (items, error) in
                        onComplete(items)
                        
                })
            }
        }
    }
}
