//
//  SongSearchModels.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 08.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SongSearch
{
    struct SongItem{
        var artistName: String
        var name: String
        var id: String
        var url: URL
    }
    
    enum Search
    {
        struct Request
        {
            var query: String
        }
        struct Response
        {
            var items: [MediaItem]
        }
        struct ViewModel
        {
            var items: [SongItem]
        }
    }
    
    enum Recent{
        struct Request
        { }
        struct Response
        {
            var items: [MediaItem]
        }
        struct ViewModel
        {
            var items: [SongItem]
        }
    }
}
