//
//  SongSearchWorker.swift
//  Rhy
//
//  Created by Roman Abuzyarov on 08.03.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SongSearchWorker
{
    let manager: AppleMusicManager
    let authorization: AuthorizationManager
    init(){
        manager = AppleManager.instance.appleMusicManager
        authorization = AppleManager.instance.authorizationManager
    }
    
    func search(for query: String, onComplete: @escaping ([MediaItem])->Void)
    {
        manager.performAppleMusicCatalogSearch(
            with: query,
            countryCode: authorization.cloudServiceStorefrontCountryCode) { (items, error) in
                if items.count > 0{
                    onComplete(items[0])
                }
        }
    }
    
    func recent(onComplete: @escaping ([MediaItem])->Void)
    {
        manager.performAppleMusicGetRecentlyPlayed(userToken: authorization.userToken, completion: { (items, error) in
            onComplete(items)
        })
    }
}
